name: Instagram Auto Poster

on:
  schedule:
    - cron: '0 */1 * * *'  # Har 1 ghante mein chalega
  workflow_dispatch:      # Manual run button

jobs:
  run_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # File save karne ki permission

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Correct Libraries
        # FIX: Hum specifically purana version install kar rahe hain taaki error na aaye
        run: |
          pip install instaloader requests "python-telegram-bot==13.15"

      - name: Run Python Script
        env:
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python main.py

      - name: Save & Update File
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          # Pehle check karenge file hai ya nahi, nahi hai to create karenge
          touch last_video.txt
          git add last_video.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update last video" && git push)
